name: 02-workflow-events
on: push

jobs:
  echo-event-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered by push event
        run: echo "This job is triggered by a ${{ github.event_name }}"
