name: 03-workflow-runners

on: push

jobs:
  runner-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Runner Information
        run: |
          echo "This job is running on a ubuntu runner."
          echo "Runner Name: ${{ runner.name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Architecture: ${{ runner.arch }}"
   runner-info-windows:
     runs-on: windows-latest
     steps:
       - name: Display Windows Runner Information
         run: |
           echo "This job is running on a windows runner."
           echo "Runner Name: ${{ runner.name }}"
           echo "Runner OS: ${{ runner.os }}"
           echo "Runner Architecture: ${{ runner.arch }}"
   runner-info-macos:
     runs-on: macos-latest
     steps:
       - name: Display macOS Runner Information
         run: |
           echo "This job is running on a macOS runner."
           echo "Runner Name: ${{ runner.name }}"
           echo "Runner OS: ${{ runner.os }}"
           echo "Runner Architecture: ${{ runner.arch }}"

