name: 05-workflow-context

on: push

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Display GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"